stages:
  - generate
  - publish

default:
  tags:
    - datenkraft
  #interruptible: true

include:
  - local: cicd/variables/main.yml
  - local: cicd/templates/*.yml
  - local: cicd/workflows/*/main.yml

# The dummy_job is needed so GitLab does not complain that the pipeline contains no jobs.
# This could happen if the includes above produce none.
dummy_job:
  stage: .pre
  script:
    - echo 'This job should never run'
    - exit 1
  rules:
    - when: never
